language: ruby
rvm:
  - rvm 2.2.1
  - rvm 2.3.1

before_script:
  - psql -c 'create database airtng_test;' -U postgres

install:
  - bundle

env:
  global:
    - TWILIO_ACCOUNT_SID=TWILIOACCOUNTSID0000
    - TWILIO_AUTH_TOKEN=TWILIOAUTHTOKEN00000
    - TWILIO_NUMBER=+12345555555
